version: "3.9"

services:
  api:
    image: zfcsoftware/cf-clearance-scraper:latest
    networks:
      - default
    restart: unless-stopped

  bot:
    build:
      context: ..
    depends_on:
      - api
    env_file:
      - ../.env
    environment:
      - CF_CLEARANCE_URL=http://api:3000/cf-clearance-scraper
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
